name: Deploy

on: [push]

jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: bounceapp/render-action@0.6.0
        with:
          node-version: 18
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cnjo1021hbls73dqsbcg
          retries: 20
          wait: 16000
